[project]
name = "archon-content-agents"

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 180"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
MEMORY_STORAGE_TYPE = "sqlite"
MEMORY_RETENTION_DAYS = "30"
MEMORY_BACKUP_ENABLED = "true"
MEMORY_BACKUP_INTERVAL = "86400"