[project]
name = "archon-content-agents"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
MEMORY_STORAGE_TYPE = "sqlite"
MEMORY_RETENTION_DAYS = "30"
MEMORY_BACKUP_ENABLED = "true"
MEMORY_BACKUP_INTERVAL = "86400"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
# Set OPENROUTER_API_KEY in Railway's dashboard environment variables